name: bookorganizer

services:
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: bookorganizer
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   # user: 1002
  django:
    image: localhost/books:latest
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - ./application:/app
      - ./data/bookorganizer:/app/data
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    environment:
      # - DATABASE_URL=postgres://postgres:postgres@db:5432/bookorganizer
      - DATABASE_URL=sqlite:////app/data/db.sqlite3
    # command: ["python", "manage.py", "makemigrations"]
    # command: ["python", "manage.py", "dumpdata"]

networks:
  bookorganizer_network:
    driver: bridge
