# Generated by Django 6.0 on 2025-12-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('official_alias', models.CharField(blank=True, default='', max_length=100)),
                ('alias', models.CharField(blank=True, default='', max_length=100)),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of where the book is stored (e.g., 'Home Library', 'Kindle')", max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Type of the media (e.g., 'Novel', 'Manga', 'Audiobook')", max_length=25)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Status of the book (e.g., 'Read', 'Currently Reading', 'Did Not Like')", max_length=25)),
                ('priority', models.SmallIntegerField(default=0, help_text='Priority of the status (higher numbers indicate higher priority)')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('missing', models.SmallIntegerField(blank=True, default=None, help_text='Number of books missing from this series', null=True)),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full title of the book', max_length=255)),
                ('progress', models.SmallIntegerField(blank=True, help_text='Reading progress (percentage or page number)', null=True)),
                ('link', models.CharField(blank=True, default='', help_text='Link or ASIN for this book', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Personal notes, thoughts, or reviews about the book')),
                ('authors', models.ManyToManyField(blank=True, default=None, help_text='Authors who wrote this book', related_name='books', to='bookorganizer.author')),
                ('location', models.ForeignKey(default=None, help_text='Where this book is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookorganizer.location')),
                ('media_type', models.ForeignKey(default=None, help_text="Type of media (e.g., 'Novel', 'Manga', 'Audiobook')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookorganizer.mediatype')),
                ('status', models.ForeignKey(default=None, help_text='Current reading status of the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookorganizer.ratings')),
                ('series', models.ForeignKey(blank=True, default=None, help_text='Series this book belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookorganizer.series')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tag.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'indexes': [models.Index(fields=['name'], name='teg_name_index')],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, help_text='Tags in the Series', to='bookorganizer.tags'),
        ),
    ]
