# Generated by Django 5.2.4 on 2025-08-04 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('bookorganizer', '0001_initial'), ('bookorganizer', '0002_author_alter_book_series_book_author'), ('bookorganizer', '0003_location_book_location'), ('bookorganizer', '0004_book_authors'), ('bookorganizer', '0005_remove_book_author'), ('bookorganizer', '0006_book_progress_alter_book_rating'), ('bookorganizer', '0007_alter_book_asin_alter_book_notes_alter_book_progress_and_more'), ('bookorganizer', '0008_alter_book_rating'), ('bookorganizer', '0009_alter_book_rating')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('missing', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.SmallIntegerField(choices=[(1, 'Not Started'), (2, 'Finished'), (3, 'On Hold'), (4, 'Dropped'), (5, 'Partial'), (6, 'Reading'), (7, 'Hated')], default=1)),
                ('asin', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('notes', models.TextField(blank=True)),
                ('series', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookorganizer.series')),
                ('location', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookorganizer.location')),
                ('authors', models.ManyToManyField(blank=True, default=None, related_name='books_authored', to='bookorganizer.author')),
                ('progress', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
