# Generated by Django 5.2.5 on 2025-08-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='asin',
            field=models.CharField(blank=True, default='', help_text='Amazon ASIN for this book', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, default=None, help_text='Authors who wrote this book', related_name='books', to='bookorganizer.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.ForeignKey(default=None, help_text='Where this book is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookorganizer.location'),
        ),
        migrations.AlterField(
            model_name='book',
            name='notes',
            field=models.TextField(blank=True, help_text='Personal notes, thoughts, or reviews about the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='progress',
            field=models.SmallIntegerField(blank=True, help_text='Reading progress (percentage or page number)', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, default=None, help_text='Series this book belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookorganizer.series'),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.ForeignKey(default=None, help_text='Current reading status of the book', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookorganizer.ratings'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Full title of the book', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(help_text="Name of where the book is stored (e.g., 'Home Library', 'Kindle')", max_length=25),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='name',
            field=models.CharField(help_text="Status of the book (e.g., 'Read', 'Currently Reading', 'Did Not Like')", max_length=25),
        ),
        migrations.AlterField(
            model_name='series',
            name='missing',
            field=models.SmallIntegerField(blank=True, default=None, help_text='Number of books missing from this series', null=True),
        ),
    ]
