# Generated by Django 5.2.5 on 2025-08-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0002_author_full_name_alter_book_asin_alter_book_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
    ]
