# Generated by Django 5.2.5 on 2025-08-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0003_remove_author_first_name_remove_author_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='priority',
            field=models.SmallIntegerField(default=0, help_text='Priority of the status (higher numbers indicate higher priority)'),
        ),
    ]
