# Generated by Django 5.2.5 on 2025-08-13 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0005_author_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Type of the media (e.g., 'Novel', 'Manga', 'Audiobook')", max_length=25)),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='media_type',
            field=models.ForeignKey(default=None, help_text="Type of media (e.g., 'Novel', 'Manga', 'Audiobook')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookorganizer.mediatype'),
        ),
    ]
