# Generated by Django 5.2.5 on 2025-08-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0006_mediatype_book_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='asin',
            new_name='link',
        ),
    ]
