# Generated by Django 5.2.5 on 2025-08-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0007_auto_20250813_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Link for this book', max_length=255, null=True),
        ),
    ]
