# Generated by Django 5.2.5 on 2025-08-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0008_alter_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='link',
            field=models.CharField(blank=True, default='', help_text='Link or ASIN for this book', max_length=255, null=True),
        ),
    ]
