# Generated by Django 5.2.5 on 2025-08-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0009_alter_book_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Full title of the book', max_length=255),
        ),
    ]
