# Generated by Django 5.2.5 on 2025-08-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0001_squashed_0009_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='missing',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
