# Generated by Django 5.2.5 on 2025-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookorganizer', '0010_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='official_alias',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
